<!Doctype html>
<html>
    <head>
        <title>Projet de demo D19.1</title>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous" />
        <style>
            h1 { text-align: center;}
            hr { 
                display: block;
                margin-top: 50px;
                margin-bottom: 50px;
                margin-left: auto;
                margin-right: auto;
                border-style: inset;
                border-width: 1px;
            }
            td { padding : 10px 10px 5px 30px;}
            th { padding-left: 30px;}
            .infos_meetup{ margin-top:50px;}
        </style>
        <script>
            $( function() {
                $( "#textinput1" ).datepicker({ dateFormat: 'yy-mm-dd' });
                $( "#textinput2" ).datepicker({ dateFormat: 'yy-mm-dd' });
            } );
        </script>
    </head>
    <body>
        <div class="container">
            <?= $content ?>
        </div>
    </body>
</html>
